#ifndef WE_WISH_YOU_A_MERRY_CHRISTMAS_H
#define WE_WISH_YOU_A_MERRY_CHRISTMAS_H
#include "notes.h"

#ifndef MELODY
#  define MELODY {NOTE_D4, NOTE_G4, NOTE_G4, NOTE_A4, NOTE_G4, NOTE_FS4, NOTE_E4, NOTE_E4, NOTE_E4, NOTE_A4, NOTE_A4, NOTE_B4, NOTE_A4, NOTE_G4, NOTE_FS4, NOTE_D4, NOTE_D4, NOTE_B4, NOTE_B4, NOTE_C5, NOTE_B4, NOTE_A4, NOTE_G4, NOTE_E4, NOTE_D4, NOTE_D4, NOTE_E4, NOTE_A4, NOTE_FS4, NOTE_G4, 0}
#else
#  error "Do not include more than one melody file!"
#endif /* MELODY */

#endif /* WE_WISH_YOU_A_MERRY_CHRISTMAS_H */
